

# rule identifiers turned on by default to exclude from running
disabled_rules:
   - trailing_whitespace
   - force_cast
   - force_unwrapping
   - force_try

excluded:
  - Centimint
  - file2
  - folder1
  - folder2/ExcludedFileFromSwiftLintRules.swift
